<Project Sdk="Microsoft.NET.Sdk">
	
    <PropertyGroup>
        <RootNamespace>TestCentric.Gui.Model</RootNamespace>
        <AssemblyName>TestCentric.Gui.Model</AssemblyName>
        <TargetFramework>net462</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>
	
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);DISABLE_MINI_GUI</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
       <Nullable>enable</Nullable>
    </PropertyGroup>
	
    <ItemGroup>
      <PackageReference Include="Nullable" PrivateAssets="all" />
	    <PackageReference Include="NUnit.Common" />
	    <PackageReference Include="NUnit.Engine" />
	    <PackageReference Include="NUnit.Extensibility" />
    </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TestCentric.Gui.Model.Tests, PublicKey=$(TestCentricPublicKey)" />
	</ItemGroup>
	
</Project>