<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<RootNamespace>TestCentric.Gui</RootNamespace>
		<AssemblyName>TestCentric.Gui.Tests</AssemblyName>
		<OutputType>Exe</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<TargetFramework>net462</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AssemblyTitle>TestCentric GUI Tests</AssemblyTitle>
    </PropertyGroup>

	<PropertyGroup>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Nullable" Version="1.3.1" PrivateAssets="all" />
	</ItemGroup>
	
	<ItemGroup>
        <ProjectReference Include="..\TestModel\TestCentric.Gui.Model.csproj" />
        <ProjectReference Include="..\TestCentric.Gui\TestCentric.Gui.csproj" />
        <ProjectReference Include="..\NUnit.UiException\NUnit.UiException.csproj" />
        <ProjectReference Include="..\..\TestData\mock-assembly\mock-assembly.csproj" />
    </ItemGroup>
       
	<ItemGroup>
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnitLite" />
	</ItemGroup>
	
</Project>