// ***********************************************************************
// Copyright (c) Charlie Poole and TestCentric contributors.
// Licensed under the MIT License. See LICENSE file in root directory.
// ***********************************************************************

using System.Drawing;
using System.Windows.Forms;

namespace TestCentric.Gui.Controls
{
    public partial class TestCentricTreeView : TreeView
    {
        // Windows style value to suppress tooltips generated by
        // the  TreeView control, so we can take control ourselves.
        private const int TVS_NOTOOLTIPS = 0x80;

        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams parms = base.CreateParams;
                parms.Style |= TVS_NOTOOLTIPS;
                return parms;
            }
        }

        protected override void OnDrawNode(DrawTreeNodeEventArgs e)
        {
            if (e.Node.IsSelected)
            {
                e.Graphics.FillRectangle(Brushes.LightGray, e.Bounds);
                TextRenderer.DrawText(e.Graphics, e.Node.Text, e.Node.NodeFont ?? Font,
                    e.Bounds, Color.Black, TextFormatFlags.Default);
            }
            else
            {
                e.DrawDefault = true;
            }
        }
    }
}
