// ***********************************************************************
// Copyright (c) Charlie Poole and TestCentric contributors.
// Licensed under the MIT License. See LICENSE file in root directory.
// ***********************************************************************

using System;
using System.Windows.Forms;

namespace TestCentric.Gui.Controls
{
    public partial class TestCentricTreeView : TreeView
    {
        // Windows style value to suppress tooltips generated by
        // the  TreeView control, so we can take control ourselves.
        private const int TVS_NOTOOLTIPS = 0x80;

        protected override CreateParams CreateParams
        {
            get
            {
                CreateParams parms = base.CreateParams;
                parms.Style |= TVS_NOTOOLTIPS;
                return parms;
            }
        }
    }
}
